### ISSUE TITLE
Feature: User can log in, or register an account

### ISSUE THREAD

**Issue by james-aguirre** [james-aguirre/ValTrade#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in or create an account
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to use the sign up or sign in page 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="516" alt="Screenshot 2023-06-08 at 3 26 11 PM" src="https://github.com/james-aguirre/Final-project/assets/121325991/46242c8c-d8eb-4886-8c4b-283f3d49380d">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `data.sql` to  include 'users' table

### ☁️ Server Tasks

- [ ] Update `server.js`  to send a post request and insert user data into the "users" table 
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to  act as the site header
- [ ] Create component to act as site footer
- [ ] Create component to display login form
- [ ] Adjust css to match wireframe if needed
- [ ] Set up base routing layout 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
